
package:
  name: s4
  version: 1.1

source:
  path: ../../

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - numpy
    - libboost
    - suitesparse
    - mkl-devel [win]
    - openblas [unix]

  host:
    - python
    - numpy
    - libboost
    - suitesparse
    - mkl-devel [win]
    - openblas [unix]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('libboost') }}
    - {{ pin_compatible('suitesparse') }}
    - {{ pin_compatible('mkl') }} [win]
    - {{ pin_compatible('openblas') }} [unix]

test:
  imports:
    - S4

about:
  home: https://web.stanford.edu/group/fan/S4/index.html
  license: GPL-2.0
  license_family: GPL
  # license_file: LICENSE.txt
  summary: 'S4 (Stanford Stratified Structure Solver) Conda Package'

  # The remaining entries in this section are optional, but recommended.
  description: |
    These are conda packages of the below software. 
    Victor Liu wrote the initial code but is not responsible for these packages.
    A program for computing electromagnetic fields in periodic, layered
    structures, developed by Victor Liu (victorliu@alumni.stanford.edu) of the
    Fan group in the Stanford Electrical Engineering Department.
    See the S4 manual, in doc/index.html, for a complete
    description of the package and its user interface, as well as
    installation instructions, the license and copyright, contact
    addresses, and other important information.
  doc_url: https://web.stanford.edu/group/fan/S4/index.html
  dev_url: https://web.stanford.edu/group/fan/S4/index.html

extra:
  recipe-maintainers:
    - marcus-o